### ISSUE TITLE
ISSUE: Multiple Locks makes too many entities and tanks HA. Also completely messes up the NabuCasa Integration

### ISSUE THREAD

**Issue by houseofbugs** [FutureTense/keymaster#269] opened 2022-03-11 03:34 UTC
**Describe the bug**
Because of all the input booleans being made it causes a HUGE lockup when you add new locks. People should disable input booleans being auto-added to the NabuCasa integration to prevent this issue.

**Environment (please complete the following information):**

- OS: HassOS
- Type of system that HA is running on: HyperV Official Appliance VM
- Home Assistant version: 2020.3.3
- Hassio: Latest
- Component version: [e.g. 0.1.2]
- Z-Wave integration name: zwave_js
- Lock make and model: n/a

Edit:

So I have 6 locks in my house. My front door is to be the parent lock. I added 3 childs and it is just completely tanking my HA installation. I had to remove the integration as this ended up making close to 2400+ entities and automations. My HA box is running on a server with a Threadripper and I have 24 cores + 32GB RAM allocated to it. It just crashes the HA box.

**Comment by houseofbugs** [comment] 2022-03-11 03:54
There has to be a better way to go about this without making so many entities and automations. The only thing I am going to try next is limiting myself to only 10 code slots even though my locks support 30.

**Comment by kaechele** [comment] 2022-05-25 16:28
Possibly a duplicate of #265

**Closed as not planned** 2023-04-21 22:21 UTC
