### ISSUE TITLE
ISSUE: unknown service: script.keymaster_frontdoor_manual_notify

### ISSUE THREAD

**Issue by HeathL17** [FutureTense/keymaster#299] opened 2022-09-09 23:17 UTC
I've been popping these errors since I moved to 2022.9.0 earlier this week.  

_The automation "keymaster_frontdoor Door Open and Close" (automation.keymaster_frontdoor_door_open_and_close) has an action that calls an unknown service: script.keymaster_frontdoor_manual_notify.

This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.

To fix this error, [edit the automation](/config/automation/edit/keymaster_frontdoor Door Open and Close) and remove the action that calls this service._

and

_The automation "keymaster_frontdoor Lock Notifications" (automation.keymaster_frontdoor_lock_notifications) has an action that calls an unknown service: script.keymaster_frontdoor_manual_notify.

This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.

To fix this error, [edit the automation](/config/automation/edit/keymaster_frontdoor Lock Notifications) and remove the action that calls this service.

Click on SUBMIT below to confirm you have fixed this automation._

Home Assistant 2022.9.1
Supervisor 2022.08.6
Operating System 8.5
Frontend 20220907.0 - latest

Keymaster is current, per HACS.

**Comment by firstof9** [comment] 2022-09-10 00:50
dupe of #295

**Closed as not planned by firstof9** 2022-09-10 00:50 UTC
Labels: duplicate
