### ISSUE TITLE
ISSUE: Code constants will be deprecated

### ISSUE THREAD

**Issue by jeprice77** [FutureTense/keymaster#392] opened 2024-10-31 19:45 UTC
Code needs changed by the time HA Core 2025.10 is released.  Constants used will be deprecated.

Here is the error log i get when HA boots up.

Logger: homeassistant.const
Source: helpers/deprecation.py:197
First occurred: 3:28:26 PM (2 occurrences)
Last logged: 3:28:26 PM

STATE_LOCKED was used from keymaster, this is a deprecated constant which will be removed in HA Core 2025.10. Use LockState.LOCKED instead, please report it to the author of the 'keymaster' custom integration
STATE_UNLOCKED was used from keymaster, this is a deprecated constant which will be removed in HA Core 2025.10. Use LockState.UNLOCKED instead, please report it to the author of the 'keymaster' custom integration

**Comment by firstof9** [comment] 2024-10-31 23:55
dupe of #386

**Closed as completed by firstof9** 2024-10-31 23:55 UTC
Labels: duplicate
