### ISSUE TITLE
ISSUE: STATE_LOCKED was used from keymaster, this is a deprecated constant which will be removed in HA Core 2025.10

### ISSUE THREAD

**Issue by cpw7922** [FutureTense/keymaster#398] opened 2024-11-24 02:03 UTC
**Describe the bug**

**Environment (please complete the following information):**

- OS: Ubuntu
- Type of system that HA is running on: PC
- Home Assistant version: 2024.11
- Hassio/Docker/Core? Docker
- Component version: v0.0.98 
- Z-Wave integration name: ZWave JS
- Lock make and model: Schlage BE469ZP

**Logs**
```
Logger: homeassistant.const
Source: helpers/deprecation.py:222
First occurred: 7:56:14 PM (2 occurrences)
Last logged: 7:56:14 PM

    STATE_LOCKED was used from keymaster, this is a deprecated constant which will be removed in HA Core 2025.10. Use LockState.LOCKED instead, please report it to the author of the 'keymaster' custom integration
    STATE_UNLOCKED was used from keymaster, this is a deprecated constant which will be removed in HA Core 2025.10. Use LockState.UNLOCKED instead, please report it to the author of the 'keymaster' custom integration
```

**Comment by firstof9** [comment] 2024-11-24 16:25
Dupe of #392

**Closed as completed** 2024-11-24 16:26 UTC
Labels: duplicate
