### ISSUE TITLE
ISSUE: 

### ISSUE THREAD

**Issue by Menz01** [FutureTense/keymaster#309] opened 2022-11-24 04:28 UTC
**Describe the bug**
I cannot add codes using this integration. always says "adding" in the lovelace cards and when i look at the entities all the code ones say unavailable. i have excluded and readded the lock with the hub sitting right next to it and it always pairs as S0 which may be a clue? its a schlage lock model BE469IR

**Environment (please complete the following information):**

- OS: 9.3 Installed on VMWare 
- Type of system that HA is running on: VMWare ESXi Dell R720
- Home Assistant version: 2022.11.4
- Hassio/Docker/Core? Core
- Component version: [e.g. 0.1.2]
- Z-Wave integration name: [e.g. zwave_js] zwave-js
- Lock make and model: [e.g. Schlage BE469] BE469IR

**Logs**
Paste your error logs here.

**Screenshots**
![image](https://user-images.githubusercontent.com/31291495/203694060-3e26aa48-95f6-45a3-badc-5d7e0682218f.png)
![image](https://user-images.githubusercontent.com/31291495/203694165-70069f64-0b3a-49e7-a744-9c2642605b9d.png)

**Additional context**
is there any other way to add codes? this lock worked fine with SmartThings and the Rboys app for adding codes but Rboy not updating i thought of trying HA and so far sad that i moved it

**Comment by firstof9** [comment] 2022-11-24 16:10
Duplicate of #270

**Closed as completed by firstof9** 2022-11-24 16:10 UTC
Labels: duplicate
