### ISSUE TITLE
ISSUE: Keymaster install on HACS is targeting HA Core minimum ver 2021.8.0b0, instead of stable.

### ISSUE THREAD

**Issue by tismondo** [FutureTense/keymaster#213] opened 2021-07-30 10:08 UTC
**Describe the bug**
Upon a fresh install of Keymaster via HACS, HACS gives me the warning ```You are running Home Assistant version '2021.7.4', but this repository requires minimum version '2021.8.0b0' to be installed.``` I am running the latest version of stable; I don't believe Keymaster is targeted only towards HA beta testers.

**Environment (please complete the following information):**

- OS: HA OS 6.1
- Type of system that HA is running on: Synology in a VM
- Home Assistant version: 2021.7.4
- Hassio/Docker/Core?  HASSIO
- Component version: n/a (not installed yet)
- Z-Wave integration name: Zwave JS
- Lock make and model: YRL256

**Logs**
N/A

**Screenshots**
https://imgur.com/a/O5A3nbK

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment] 2021-07-30 13:16
The latest version of KeyMaster requires 2021.8.x or higher due to code changes.

**Comment by firstof9** [comment] 2021-07-30 13:19
Dupe of #210

**Closed as completed** 2021-07-30 13:19 UTC
Labels: duplicate, wontfix
