### ISSUE TITLE
Keymaster_front_door User Notification uses an unknown service

### ISSUE THREAD

**Issue by dcerny1** [FutureTense/keymaster#297] opened 2022-09-09 20:29 UTC
Keymaster_front_door User Notification uses an unknown service

The automation "keymaster_front_door User Notifications" (automation.keymaster_front_door_user_notifications) has an action that calls an unknown service: script.keymaster_front_door_manual_notify.

This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.

To fix this error, [edit the automation](/config/automation/edit/keymaster_front_door User Notifications) and remove the action that calls this service.

Click on SUBMIT below to confirm you have fixed this automation.

**Environment (please complete the following information):**

- OS: HassOS
- Type of system that HA is running on: VMWare Workstation Player 16 under Windows 10
- Home Assistant version:  Home Assistant 2022.9.1
-  Supervisor 2022.08.6 
- Operating System 8.5 
- Frontend 20220907.0 - latest 
- Component version: 0.0.82
- Z-Wave integration name: zwave-js
- Lock make and model: Schlage BE469]

**Logs**
2022-09-09 13:48:04.081 ERROR (MainThread) [homeassistant.components.automation.keymaster_front_door_user_notifications] keymaster_front_door User Notifications: Error executing script. Service not found for call_service at pos 1: Unable to find service script.keymaster_front_door_manual_notify 

**Screenshots**

**Additional context**
I first noticed this error after updating to Home Assistant Core 2022.9.0 and after installing InfluxDB and Grafana. Don't see how any of these would have any effect on missing service script.keymaster_front_door_manual_notify. Looking through the custom components for keymaster, I see this service used several times, but never defined.

**Comment by firstof9** [comment] 2022-09-09 21:39
dupe of #295

**Closed as not planned by firstof9** 2022-09-09 21:39 UTC
Labels: duplicate
