### ISSUE TITLE
ISSUE: module 'homeassistant.components.mqtt.models' has no attribute 'Message'

### ISSUE THREAD

**Issue by MrMxyzptlk** [FutureTense/keymaster#209] opened 2021-07-29 10:00 UTC
Click on add Integration after install from HACS and restart; "Installing Keymaster...could not load config flow".

ODROID-N2+ Home Assistant Bundle - Blue

2021-07-29 05:50:15 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 128, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 171, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 696, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/keymaster/__init__.py", line 30, in <module>
    from .binary_sensor import generate_binary_sensor_name
  File "/config/custom_components/keymaster/binary_sensor.py", line 219, in <module>
    class OZWNetworkReadySensor(BaseNetworkReadySensor):
  File "/config/custom_components/keymaster/binary_sensor.py", line 229, in OZWNetworkReadySensor
    def async_check_ozw_status(self, msg: models.Message):
AttributeError: module 'homeassistant.components.mqtt.models' has no attribute 'Message'
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.50.109'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

![Screen Shot 2021-07-29 at 5 57 57 AM](https://user-images.githubusercontent.com/1753001/127472427-d32034e6-f5c0-4144-af26-8a2d2a8bbd5a.png)

![Screen Shot 2021-07-29 at 5 59 49 AM](https://user-images.githubusercontent.com/1753001/127472581-e51af861-6331-4509-9375-c627865a6403.png)

**Comment by firstof9** [comment] 2021-07-29 13:30
Dupe of #208

**Comment by raman325** [comment] 2021-07-29 15:31
yep you must be on the beta. We will release a beta supported version of keymaster soon

**Closed as completed** 2021-07-29 15:54 UTC
Labels: duplicate
