### ISSUE TITLE
ISSUE: 

### ISSUE THREAD

**Issue by krusej23** [FutureTense/keymaster#311] opened 2022-11-27 02:41 UTC
I have notifications setup for when a pin code is used to unlock the door. When I unlock the door, I get an error message saying the below...

> keymaster_frontdoorlock Lock Notifications uses an unknown service
> The automation "keymaster_frontdoorlock Lock Notifications" (automation.keymaster_frontdoorlock_lock_notifications) has an action that calls an unknown service: script.keymaster_frontdoorlock_manual_notify.
> 
> This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.
> 
> To fix this error, [edit the automation](/config/automation/edit/keymaster_frontdoorlock Lock Notifications) and remove the action that calls this service.
> 
> Click on SUBMIT below to confirm you have fixed this automation.

- OS: HassOS
- Type of system that HA is running on: Windows
- Home Assistant version: Home Assistant 2022.11.4
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest
- Hassio/Docker/Core?
- Component version: [e.g. 0..0.82]
- Z-Wave integration name: zwave_js
- Lock make and model: Schlage

**Logs**
keymaster_frontdoorlock Lock Notifications uses an unknown service
The automation "keymaster_frontdoorlock Lock Notifications" (automation.keymaster_frontdoorlock_lock_notifications) has an action that calls an unknown service: script.keymaster_frontdoorlock_manual_notify.

This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.

To fix this error, [edit the automation](/config/automation/edit/keymaster_frontdoorlock Lock Notifications) and remove the action that calls this service.

Click on SUBMIT below to confirm you have fixed this automation.

**Screenshots**
<img width="765" alt="Screen Shot 2022-11-26 at 8 14 11 PM" src="https://user-images.githubusercontent.com/10549869/204116812-353609ae-024d-4104-b5ec-02857dcc635b.png">

**Comment by firstof9** [comment] 2022-11-27 02:44
Dupe of #295

**Closed as completed by firstof9** 2022-11-27 02:44 UTC
Labels: duplicate
