### ISSUE TITLE
ISSUE: HA 2022.9.1 Automatic Issue Reported

### ISSUE THREAD

**Issue by curt7000** [FutureTense/keymaster#296] opened 2022-09-09 15:22 UTC
**Describe the bug**
After updating to HA 2022.9.1, the new automatic issue identification/resolver in HA is reporting a issue, “keymaster_lock Lock Notifications uses an unknown service”

**Environment (please complete the following information):**

- OS: Ubuntu 22.04 LTS
- Type of system that HA is running on: Hyper-V VM
- Home Assistant version: 2022.9.1
- Hassio/Docker/Core?: Core VENV Python 3.9
- Component version: 0.0.82
- Z-Wave integration name: zwave_js
- Lock make and model: Impacting all Kwikset & Yale locks

**Logs**
The automation "keymaster_front_door Lock Notifications" (automation.keymaster_front_door_lock_notifications) has an action that calls an unknown service: script.keymaster_front_door_manual_notify.

This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.

To fix this error, [edit the automation](/config/automation/edit/keymaster_front_door Lock Notifications) and remove the action that calls this service.

Click on SUBMIT below to confirm you have fixed this automation.

**Comment by firstof9** [comment] 2022-09-09 15:39
dupe of #295

**Closed as not planned by firstof9** 2022-09-09 15:39 UTC
Labels: wontfix
